### ISSUE TITLE
Multiple pending patches and requests on forum

### ISSUE THREAD

**Issue by danielg4** [inniyah/pianobooster#1]
Hi! You might want to coordinate your efforts with the PianoBooster forum:
http://piano-booster.2625608.n2.nabble.com
Before noticing your repo, I did something unfortunately in parallel:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841785
I know that the pieces to pick up are rather scattered, but I think even the smallest things could help.

**Comment by glixx** [comment]
Follow https://github.com/captnfab/PianoBooster
